### ISSUE TITLE
Only allow reservations between 8AM and 8PM

### ISSUE THREAD

**Issue by HyimHK** [CGU-IST303/IST303F19-Prj-Team-1#20]
1. Need to define the schema of the RESERVATION and SERVICES
2. Need a collection of columns:
 | guest_id | date_time |  service_id | duration |
Cost and duration live on the services class

**Comment by jarvis5674** [comment]
Create a class called Day

**Comment by jarvis5674** [comment]
Use this issue to support issue #37

**Comment by jarvis5674** [comment]
Verified this works by running the program. Need to make sure string works fully, but is giving out the correct messages.
