### ISSUE TITLE
Prevent guest signing into MiYE

### ISSUE THREAD

**Issue by HyimHK** [CGU-IST303/IST303F19-Prj-Team-1#23]

**Comment by jtylermp** [comment]
I think something like this code can be implemented for a login screen and disallowing guests to use the system

https://stackoverflow.com/questions/22170848/simple-login-program-in-python

**Comment by jtylermp** [comment]
https://stackoverflow.com/questions/28483113/simple-login-function-in-python

moving to use a txt file so that multiple logins will be capable

**Comment by jtylermp** [comment]
@HyimHK what do you think??
[Usernames.txt](https://github.com/CGU-IST303/IST303F19-Prj-Team-1/files/3722121/Usernames.txt)

**Comment by HyimHK** [comment]
@jtylermp looks good!

**Comment by HyimHK** [comment]
@jtylermp use 
```
from getpass import getpass

getpass()
```

This will get the password secretly from the user.
