### ISSUE TITLE
The ability to list all reservations/cancellations for any service for any weekly period

### ISSUE THREAD

**Issue by HyimHK** [CGU-IST303/IST303F19-Prj-Team-1#93]
This is a management tool to be able to understand better which services are being used and when. This should be designed so as to make use and non-use easy to see at a glance. Each report should be for a specified service (e.g., a 30-minute Swedish massage) for a specified Sunday-Saturday period: either the current one or some past one for which data exists.

**Comment by jarvis5674** [comment]
method for the admin 
a user inputs 10 and able to list all reservations and cancellations

**Comment by jarvis5674** [comment]
Done!
